version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node
    working_directory: ~/prickathon.github.io

  workspace_root: &workspace_root
      /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v2-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-v2-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command:
            npm run generate
            && mkdir -p /tmp/workspace
            && cp -r dist /tmp/workspace
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist
  deploy:
    <<: *container_config
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Set Git configure
          command:
            git config --global user.email "$GH_EMAIL" > /dev/null 2>&1 &&
            git config --global user.name "$GH_NAME" > /dev/null 2>&1
      - run:
          name: Deploy to master
          command: npx push-dir --dir=/tmp/workspace/dist --branch=master --cleanup

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: dev
